"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight, DatabaseZap, ExternalLink, LoaderCircle } from "lucide-react";

type Asset = { id: string; runId: string; content: { project: string; run: string; lessons: string[]; finalVersion: string }; ual: string | null; network: string | null; status: string; publishedAt: string | null };

export default function KnowledgePage() {
  const [assets, setAssets] = useState<Asset[] | null>(null);
  useEffect(() => { fetch("/api/knowledge", { cache: "no-store" }).then((res) => res.json()).then((data: { assets: Asset[] }) => setAssets(data.assets)); }, []);
  return <main className="relative min-h-[100dvh] overflow-hidden bg-[#09090b] px-5 py-5 text-foreground md:px-10"><div className="pointer-events-none absolute inset-0 opacity-20" style={{ backgroundImage: "radial-gradient(circle at 2px 2px, rgba(255,255,255,0.15) 1px, transparent 0)", backgroundSize: "32px 32px" }} /><div className="relative z-10 mx-auto max-w-[1160px]"><Header /><div className="py-16 md:py-24"><div className="flex items-start justify-between gap-8"><div><div className="inline-flex items-center gap-2 rounded-full border border-border bg-card/70 px-3 py-1.5 font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground"><span className="size-1.5 rounded-full bg-primary" /> OriginTrail memory</div><h1 className="mt-6 max-w-3xl text-5xl font-semibold leading-[0.98] tracking-[-0.065em] md:text-7xl">What Liverloop remembers.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Selected lessons from completed production runs, published as verifiable Knowledge Assets rather than hidden application logs.</p></div><DatabaseZap className="mt-3 hidden size-9 text-primary md:block" /></div><div className="mt-16">{assets === null ? <div className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground"><LoaderCircle className="size-4 animate-spin text-primary" /> Loading published assets</div> : assets.length === 0 ? <EmptyKnowledge /> : <div className="grid gap-4">{assets.map((asset, index) => <motion.div key={asset.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.06 }}><AssetCard asset={asset} /></motion.div>)}</div>}</div></div></div></main>;
}

function Header() { return <header className="flex items-center justify-between rounded-full border border-border bg-card/70 px-4 py-3 shadow-xl shadow-black/10 backdrop-blur-xl md:px-5"><Link href="/" className="flex items-center gap-3 font-mono text-sm tracking-[0.16em]"><span className="flex size-7 items-center justify-center rounded-md bg-primary text-primary-foreground"><span className="size-2 rounded-full bg-current" /></span>LIVERLOOP</Link><div className="flex items-center gap-4"><Link href="/provenance" className="text-xs text-muted-foreground hover:text-foreground">Provenance</Link><Link href="/run/new" className="inline-flex items-center gap-2 rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground hover:text-foreground">New run <ArrowUpRight className="size-3" /></Link></div></header>; }

function EmptyKnowledge() { return <div className="rounded-2xl border border-dashed border-border bg-card/30 p-12 text-center"><DatabaseZap className="mx-auto size-7 text-muted-foreground" /><p className="mt-5 text-sm text-muted-foreground">No published Knowledge Assets yet.</p><p className="mt-2 text-xs text-muted-foreground/70">Complete a real run with a funded OriginTrail wallet to create one.</p></div>; }

function AssetCard({ asset }: { asset: Asset }) { return <article className="rounded-2xl border border-border bg-card/65 p-5 shadow-2xl shadow-black/20 backdrop-blur-xl md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground"><span className={`size-1.5 rounded-full ${asset.status === "published" ? "bg-primary" : "bg-amber-300"}`} /> {asset.status === "published" ? "Published / real" : "Publication failed"}</div><h2 className="mt-4 text-2xl font-semibold tracking-[-0.04em]">Run {asset.content.run}</h2></div>{asset.ual ? <a href="https://dkg-testnet.origintrail.io/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-border px-3 py-2 font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground hover:text-foreground">Verify on DKG <ExternalLink className="size-3" /></a> : null}</div><div className="mt-8 grid gap-8 md:grid-cols-[0.8fr_1.2fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Lessons retained</p><ul className="mt-4 space-y-3">{asset.content.lessons.map((lesson) => <li key={lesson} className="flex gap-3 text-sm leading-6 text-foreground/80"><span className="mt-2 size-1 shrink-0 rounded-full bg-primary" />{lesson}</li>)}</ul></div><div className="border-l border-border pl-6 md:pl-8"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Asset evidence</p><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-4 border-b border-border pb-3"><dt className="text-muted-foreground">Network</dt><dd className="font-mono text-xs">{asset.network ?? "unavailable"}</dd></div><div className="flex justify-between gap-4 border-b border-border pb-3"><dt className="text-muted-foreground">Final version</dt><dd className="font-mono text-xs">{asset.content.finalVersion}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">UAL</dt><dd className="max-w-[24ch] truncate font-mono text-xs">{asset.ual ?? "not published"}</dd></div></dl></div></div></article>; }
