"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowUpRight, DatabaseZap, ExternalLink, LoaderCircle } from "lucide-react";

type Asset = { id: string; runId: string; content: { project: string; run: string; lessons: string[]; finalVersion: string }; ual: string | null; network: string | null; status: string; publishedAt: string | null };

export default function KnowledgePage() {
  const [assets, setAssets] = useState<Asset[] | null>(null);
  useEffect(() => { fetch("/api/knowledge", { cache: "no-store" }).then((res) => res.json()).then((data: { assets: Asset[] }) => setAssets(data.assets)); }, []);
  return <main className="min-h-[100dvh] px-5 py-6 md:px-10"><div className="mx-auto max-w-[1160px]"><header className="flex items-center justify-between border-b border-border pb-5"><Link href="/" className="font-mono text-sm tracking-[0.16em]">LIVERLOOP</Link><Link href="/run/new" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">New run <ArrowUpRight className="size-4" /></Link></header><div className="py-16 md:py-24"><div className="flex items-start justify-between gap-8"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary">Durable memory / OriginTrail</p><h1 className="mt-5 text-5xl font-semibold tracking-[-0.06em] md:text-6xl">What Liverloop remembers.</h1><p className="mt-6 max-w-xl leading-7 text-muted-foreground">Selected lessons from completed production runs, published as verifiable Knowledge Assets rather than hidden application logs.</p></div><DatabaseZap className="mt-3 hidden size-8 text-primary md:block" /></div><div className="mt-16">{assets === null ? <div className="flex items-center gap-3 text-sm text-muted-foreground"><LoaderCircle className="size-4 animate-spin" /> Loading published assets</div> : assets.length === 0 ? <div className="rounded-xl border border-dashed border-border p-10 text-sm text-muted-foreground">No published Knowledge Assets yet. Complete a real run to create one.</div> : <div className="grid gap-4">{assets.map((asset) => <AssetCard key={asset.id} asset={asset} />)}</div>}</div></div></div></main>;
}

function AssetCard({ asset }: { asset: Asset }) { return <article className="rounded-xl border border-border bg-card/45 p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground"><span className={`size-1.5 rounded-full ${asset.status === "published" ? "bg-primary" : "bg-amber-300"}`} /> {asset.status === "published" ? "Published / real" : "Publication failed"}</div><h2 className="mt-4 text-2xl font-semibold tracking-[-0.04em]">Run {asset.content.run}</h2></div>{asset.ual ? <a href={`https://dkg-testnet.origintrail.io/`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground hover:text-foreground">Verify on DKG <ExternalLink className="size-3" /></a> : null}</div><div className="mt-8 grid gap-8 md:grid-cols-[0.8fr_1.2fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Lessons retained</p><ul className="mt-4 space-y-3">{asset.content.lessons.map((lesson) => <li key={lesson} className="flex gap-3 text-sm leading-6 text-foreground/80"><span className="mt-2 size-1 shrink-0 rounded-full bg-primary" />{lesson}</li>)}</ul></div><div className="border-l border-border pl-6 md:pl-8"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Asset evidence</p><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-4 border-b border-border pb-3"><dt className="text-muted-foreground">Network</dt><dd className="font-mono text-xs">{asset.network ?? "unavailable"}</dd></div><div className="flex justify-between gap-4 border-b border-border pb-3"><dt className="text-muted-foreground">Final version</dt><dd className="font-mono text-xs">{asset.content.finalVersion}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted-foreground">UAL</dt><dd className="max-w-[24ch] truncate font-mono text-xs">{asset.ual ?? "not published"}</dd></div></dl></div></div></article>; }
